### ISSUE TITLE
Turn sidebar menu into Bottom Navigation on mobile

### ISSUE THREAD

**Issue by m3h0w** [m3h0w/covid19-coronavirus-react-visualization#4]
Use [Bottom Navigation](https://material-ui.com/components/bottom-navigation/) on mobile to give more space for graphs and the map.

**Comment by akinhwan** [comment]
hey joining in from slack, i just forked and am going to look into this.

**Comment by m3h0w** [comment]
> hey joining in from slack, i just forked and am going to look into this.

Cool!

One thing to note is that between adding this issue and now, I added share buttons that on mobile move to empty space in the left navigation bar. So they have to be placed somewhere else. My idea would be to just add another card on the very bottom of each subpage with these share buttons that is `<Hidden smUp>`. 

And I guess that leaves the github button having to be placed somewhere else too, but I'm sure you can figure something nice out.

Let me know if I can be of any help :)

**Comment by akinhwan** [comment]
is there a reason why you use `<Drawer variant='permanent'> 
because if it wasn't permanent then it would save space on mobile?
There is also a way to make the Drawer on the bottom?

**Comment by m3h0w** [comment]
Just that I like the navigation being accessible without having to open the drawer. 

And yes, you can use the element that I linked to in the issue: https://material-ui.com/components/bottom-navigation/ to display mobile-style navigation on devices xsDown or smDown (according to Material UI definitions)

**Comment by akinhwan** [comment]
by the way have I mentioned I primarily use Vue for everything, and React is a bit new to me. So forgive me if I'm a bit slow at this

**Comment by m3h0w** [comment]
No worries - let me know if you need some help

**Comment by akinhwan** [comment]
@m3h0w Hey Michael I'm sorry I really wanted to help with this amazing site, but looks like I have to reprioritize some things in my life at the moment. I won't be participating in the hackathon after all. Thank you for making this and wish you the best in continued development!

**Comment by loxator** [comment]
@m3h0w Hi, I am here from Slack and have messaged you there as well. This is what I have so far, please reply here (for documentation) or in slack and let me know if this works, thanks!
![image](https://user-images.githubusercontent.com/18169190/78501665-a022d780-776d-11ea-9af6-bbab9f896435.png)

**Comment by m3h0w** [comment]
Hi @loxator! Thanks for taking an interest :)

The card looks good (assuming readjusted spacing, text positioning, and icon sizes to better fit the space) - that's what I indeed had in mind for the social icons. What about the BottomNavigation?

**Comment by loxator** [comment]
@mehow I thought you wanted it in a card since you mentioned it earlier in one of the comments. Do you want me to change this from a card to a BottomNavigation component?

**Comment by m3h0w** [comment]
Merged in #27
