### ISSUE TITLE
Mortality Rate

### ISSUE THREAD

**Issue by ehmjaysee** [m3h0w/covid19-coronavirus-react-visualization#6]
This chart is using the label "Motality rate (world)" (note: this is mispelled)
The rate is calculated as Deaths / Confirmed Cases
This is NOT the mortality rate. This is the "case fatality rate" or CFR. Please revise the chart. 
https://en.wikipedia.org/wiki/Case_fatality_rate
https://en.wikipedia.org/wiki/Mortality_rate

**Comment by m3h0w** [comment]
Thank you for the clarification. I fixed it immediately.

Please feel free to point out any other inaccuracies to be fixed or improvements you'd like to see.
